### ISSUE TITLE
Unknown class KWDrawerController in Interface Builder file.

### ISSUE THREAD

**Issue by husnaintahir** [kawoou/KWDrawerController#11]
First of all thanks for the great library.

I am having an issue, when i set Custom Class to "KWDrawerController" via story board there is no build issue only the console show this message "Unknown class KWDrawerController in Interface Builder file."

I have removed the libs via pods and installed many times but still the same issue.

Hoping for quick response.

Thanks.

**Comment by kawoou** [comment]
I want you to let me know a little clearer situation.
For example, do not use Cocoapods, or main project language is ObjC.

**Comment by husnaintahir** [comment]
I am using cocoapods and main project language is swift.

**Comment by kawoou** [comment]
Well... does it work if I put @objc on the KWDrawerController class?
