### ISSUE TITLE
Crashed on load

### ISSUE THREAD

**Issue by jeffayan** [kawoou/KWDrawerController#12]
Attempting to load the view of a view controller while it is deallocating is not allowed and may result in undefined behavior (<KWDrawerController.DrawerController: 0x7f9e23978a00>)

<img width="1045" alt="screen shot 2018-01-29 at 2 01 48 am" src="https://user-images.githubusercontent.com/17008251/35486742-728df1b4-0498-11e8-85b9-c5bde46878aa.png">

**Comment by kawoou** [comment]
Under what circumstances does the crash occur?

**Comment by Jeff-KaayLabs** [comment]
When tried to present this view controller after login

**Comment by kawoou** [comment]
Can you tell me which version of iOS or Swift you are using?

**Comment by kawoou** [comment]
I found the cause.
I will update 4.1.3 after fixing issues.

**Comment by kawoou** [comment]
released 4.1.3!

**Comment by Jeff-KaayLabs** [comment]
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "KWDrawerController":
  In Podfile:
    KWDrawerController (~> 4.1.3)

None of your spec sources contain a spec satisfying the dependency: `KWDrawerController (~> 4.1.3)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
