### ISSUE TITLE
Set status bar style

### ISSUE THREAD

**Issue by Serproger** [kawoou/KWDrawerController#13]
Now default status bar style (black) is used for DrawerController . To change the style, I have to write something like that:
```
extension DrawerController {
 open override var preferredStatusBarStyle: UIStatusBarStyle {
  return UIStatusBarStyle.lightContent
 }
}
```

Please add possibility to set status bar style via initializer or property of DrawerController class. And it would be great to get default status bar style (if it hasn't been set explicitly) as status bar style of content controller.

**Comment by kawoou** [comment]
Is there no processing for the status bar in the current implementation?
If so, I would have missed out on implementing ObjC as a Swift version.

I will implement this additionally.
Thank you for your feedback.
