### ISSUE TITLE
Width of side menu as percentage

### ISSUE THREAD

**Issue by Serproger** [kawoou/KWDrawerController#14]
Now I can set drawer width only in points. Because of that, side menu doesn't adapt to changes of size width. For example, I can't make menu occupying one third of screen without writing custom code that will update menu width when size of screen changes.
It would be useful to specify side menu width as percentage of screen width. Maybe can you suggest some way to use Auto Layout for side menu size determination?

**Comment by kawoou** [comment]
If you register PR, I will review it 😆
