### ISSUE TITLE
Observe state with delegate

### ISSUE THREAD

**Issue by 0xch4z** [kawoou/KWDrawerController#15]
Thanks for the library! It would be cool if there was a delegate protocol to preform actions on the drawer state changing rather than having to pass a completion handler in. For example, the following stubs:

```swift
func drawerController?(willOpenSide side: DrawerSide)

func drawerController?(willCloseSide side: DrawerSide)
```

I'd be happy to submit a PR.

Thanks,
Charles

**Comment by kawoou** [comment]
Sounds like a good idea😆
Do I add this? Or if you would like to upload your own PR, I'll be happy to review.

**Comment by 0xch4z** [comment]
Sweet, thanks. Just added PR #16. Already using this in my own project and it's a big help for changing the status bar color when the drawer is open.

Let me know if I need to change anything!
