### ISSUE TITLE
Unable to get delegates to fire

### ISSUE THREAD

**Issue by ttupper92618** [kawoou/KWDrawerController#19]
Is there an example of using the delegates somewhere?  I'm having trouble getting any delegate method to fire, and I badly need to be able to respond to drawer state as it changes.

**Comment by ttupper92618** [comment]
I worked around this using notificationCenter, but it would still be nice to understand the proper way to consume the delegate methods.  Ostensibly, conforming the view and including the delegate methods should work, correct?  But that does not in fact happen; delegates are never called.

I do not want to use rxSwift.

**Comment by kawoou** [comment]
If you do not use RxSwift, try this:
```
pod 'KWDrawerController/Core'
```

Delegates are not called issues are also resolved in this way.
