### ISSUE TITLE
pod install issue

### ISSUE THREAD

**Issue by seon1-k** [kawoou/KWDrawerController#2]
i can't install this framework with below message...

[!] Unable to satisfy the following requirements:

- `KWDrawerController (~> 3.6.1)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `KWDrawerController (~> 3.6.1)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

so i tried to install with 'pod 'KWDrawerController'' but pod tried install 3.3 version.

**Comment by kawoou** [comment]
There is a good answer from StackOverflow about this issue.

[pod repo update does not happen error in cocoapods](https://stackoverflow.com/questions/38030317/pod-repo-update-does-not-happen-error-in-cocoapods)

Try that!
