### ISSUE TITLE
When closing a side panel presented using DrawerFloatTransition, the primary view is sometimes re-presented offset to the left

### ISSUE THREAD

**Issue by ttupper92618** [kawoou/KWDrawerController#20]
When closing a side panel that has been presented using a DrawerFloatTransition, the main view controller is not always restored properly and is instead drawn offset to the left by approximately 30 pixels.  This creates a visual defect in the UI.  Subsequent open / close of the side panel will exacerbate the situation, eventually causing the primary view to become unusable.

See images below:

![one](https://user-images.githubusercontent.com/11300465/38060326-16a5dc4c-329f-11e8-9d73-4d5f89c562a0.png)
![two](https://user-images.githubusercontent.com/11300465/38060329-189b7dcc-329f-11e8-9f59-6f3e99b99462.png)
![three](https://user-images.githubusercontent.com/11300465/38060330-1a26a55e-329f-11e8-90fe-13d56805d3d7.png)

**Comment by kawoou** [comment]
Is this an issue only on iPhone X?

**Comment by kawoou** [comment]
It's not an X problem. Under what circumstances?

**Comment by ttupper92618** [comment]
Not iPhone X only - it is however MUCH worse on an iPhone X.  I can typically trigger it very infrequently on devices like 6S, etc. by opening and closing the left VC repeatedly.  It happens virtually every time on an iPhone X.  But I cannot find a 100% path for reproducing it; it seems to happen when actuating the left VC using a button action:

```
@IBAction func auiShowNav(_ sender: UIButton) {
        self.drawerController?.setTransition(DrawerFloatTransition(), for: .left)
        self.drawerController?.setOverflowTransition(DrawerFloatTransition(), for: .left)
        self.drawerController?.openSide(.left)
        auiOcclusionMask.isHidden = false       
}
```
