### ISSUE TITLE
drawerController is null in viewWillDisappear and viewDidDisappear

### ISSUE THREAD

**Issue by Serproger** [kawoou/KWDrawerController#21]
Extension property drawerController of UIViewController returns nil when I'm trying to access it in viewWillDisappear and viewDidDisappear methods of my view controller. Could you please explain this behaviour if it's correct or fix it if there is some bug?

**Comment by kawoou** [comment]
The situation is not reproduced. Can you tell me what circumstances?

**Comment by Serproger** [comment]
This issue can be observed when UINavigationController is located inside DrawerController, I have controllers A and B in navigation stack and I press back button in B. ViewWillDisappear and ViewDidDisappear of B will be called, but in both of them drawerController property is equal to nil. If necessary, I'll prepare sample project.

**Comment by Serproger** [comment]
UPD. Sorry, in this case the problem doesn't reproduce. I'll prepare another sample sample.

**Comment by kawoou** [comment]
If that's what I understand:
```
DrawerController <- UINavigationController
  UINavigationController <- A
  UINavigationController <- B
```
Since A and B are not managed directly by DrawerController, `nil` value is correct.

However, the `drawerController` property of the UINavigationController will be not `nil`.

**Comment by Serproger** [comment]
But in other lifecycle methods drawerController is not `nil`...

**Comment by kawoou** [comment]
What is "other lifecycle"?

**Comment by Serproger** [comment]
for example, `viewDidLoad`.

**Comment by kawoou** [comment]
I extended the range of drawerController property. #25
Is there a problem now?

**Comment by Serproger** [comment]
[drawertest1.zip](https://github.com/kawoou/KWDrawerController/files/1920156/drawertest1.zip)

Please see controller InnerContentController1 in this sample. drawerController is not nil in viewWillDisappear but it is nil in viewDidDisappear.

**Comment by Serproger** [comment]
You should press button "GO", then button "Button", then press back button in navigation controller to reproduce.

**Comment by kawoou** [comment]
I have tested the code.
In viewDidDisappear, it is normal for the drawerController variable to be nil.
Because there is no parentViewController at the time when viewDidDisappear is called.

**Comment by Serproger** [comment]
OK, maybe it's the feature, not bug :)

Please update package in Cocoapods.
