### ISSUE TITLE
DrawerController incorrectly manages lifecycles of child controllers

### ISSUE THREAD

**Issue by Serproger** [kawoou/KWDrawerController#22]
Please see attached project. I have initial view controller with button "Go". When I press this button, I initialize DrawerController, set SideMenuController as side menu and InnerContentController as content, and set DrawerController as root window controller. Pressing "Go button" produces console output:
```
inner content controller will disappear
inner content controller did disappear
inner content controller will appear
side menu controller will appear
inner content controller did appear
side menu controller did appear
```

But InnerContentController has never disappeared of course. And SideMenuController has never appeared. The console output should be as follows:
```
inner content controller will appear
inner content controller did appear
```

So, lifecycles of child controllers are managed by DrawerController incorrectly. I have a much bigger application, and in this application method viewDidAppear of some controller inside DrawerController isn't getting called. Because of that, my important code in this method is not executed. Without DrawerController, all works fine.

Please fix this, it is the critical problem.

[drawertest.zip](https://github.com/kawoou/KWDrawerController/files/1915247/drawertest.zip)

**Comment by kawoou** [comment]
Sounds right.
I will modify events such as viewDidAppear to be managed by UIKit.
