### ISSUE TITLE
Allow DrawerTransition subclass

### ISSUE THREAD

**Issue by dvkch** [kawoou/KWDrawerController#3]
Hello,

I just discovered this project and find it very interesting, and very well done. However I'd like to implement a custom transition (sliding left side, with fixed center VC masked by shadow + semi-opaque color), which is not currently possible because the base class is not defined as public.

Would it be possible to declare it public? Also if you think there will be an issue with implementing the transition I'm looking for and have a quick fix that would be very appreciated; if you don't have the time I can send a PR your way when I've had the chance to try.

Thanks a lot for your time,

Stan

**Comment by kawoou** [comment]
Hello,

I read the issue well.
In creating a custom transition, is there a problem where the base class is not defined as public?

It would be nice if you can give me some more details about custom transitions.

Thank you.

Kawoou
