### ISSUE TITLE
Only left drawer.

### ISSUE THREAD

**Issue by Rogho** [kawoou/KWDrawerController#35]
HI, I want to enable only left drawer. How can I do that?

**Comment by kawoou** [comment]
Register the ViewController to the left only, or change the options.

```swift
drawerController?.getSideOption(for: .right)?.isEnable = false
```

**Comment by Rogho** [comment]
thank you!

**Comment by rhangad** [comment]
Hi @kawoou I tried `drawerController?.getSideOption(for: .right)?.isEnable = false` but the right side can still be opened by gesture
