### ISSUE TITLE
Slide animation bug

### ISSUE THREAD

**Issue by bdobreav** [kawoou/KWDrawerController#38]
Hi, I am seeing a random bug that is reproducible only on a device (tested on iPhone 5S and 7)
I am using your example, without any modifications. The issue is that sometimes, when I press the button to open the right drawer (transition is set to Slide), the drawer opens up fine, but sometimes the slide animation stutters and the side viewcontroller is offset to the left of the screen (notice that the main viewcontroller underneath it remains at its initial position)

![right](https://user-images.githubusercontent.com/8884361/53003838-8f63b500-3438-11e9-8c37-807652e9309a.PNG)
![wrong](https://user-images.githubusercontent.com/8884361/53003847-94c0ff80-3438-11e9-9398-de2b2e9405fe.PNG)

**Comment by kawoou** [comment]
In the example, both have different default settings.
This is not a bug.

**Comment by bdobreav** [comment]
Hi. What do you mean by "both"? I'm only pressing the top right button, so only the right drawer appears. I have recorded my iPhone screen (iPhone 7, iOS 12.1.2), please take a look. It has to be a bug, this can't be normal. Your example project is built with XCode 10.1

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/8884361/53069908-36525a80-34e6-11e9-95a1-c92dbddb9581.gif)

The only way to reproduce it is to wait a couple of seconds with the app in the foreground, and then try to open the drawer again. Sometimes it behaves strangely. I have also seen a similar issue with other drawer animation types.

**Comment by Heshanpm** [comment]
I'm experiencing this issue randomly when the device has automatic rotation on. When it's off this never happens. Figured out any solution? I suggest re-opening this issue.

**Comment by Heshanpm** [comment]
To recreate the issue, turn automatic rotation on -> change the orientation of the device -> open the drawer with a button action. Hope this helps to resolve the issue.

**Comment by Rajib-Sarwar** [comment]
Did anyone fine any solution for this drawer sliding bug?
For the first time the right navigation drawer moved to left side
