### ISSUE TITLE
preferredStatusBarStyle

### ISSUE THREAD

**Issue by dvkch** [kawoou/KWDrawerController#4]
Hi there,

After some tests I realized that `preferredStatusBarStyle` and similar where not set from the currently displayed side, it would be nice to forward them and ask the system for a status bar update when opening/closing a side.

Would you like a PR?

Thanks again,

Stan

**Comment by kawoou** [comment]
Hello @dvkch!
First, thank you very much for using this project :)

Thank you for letting us know about this issue.
It would be nice if you PR your wonderful work.

Thanks again,

Kawoou
