### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by aiswaryamanal** [kawoou/KWDrawerController#7]
No idea about how to implement KWDrawerController. And it is not working and it produces a black screen

**Comment by kawoou** [comment]
Could you tell me the path to reappear?

**Comment by aiswaryamanal** [comment]
Now it does not produce black screen. But side menus not working
I think that usage of KWDrawer controller is not clear.  I have used push instead of custom and not given any code in appdelegate. Now i got main view controller appeared but side menus not working

**Comment by kawoou** [comment]
Did you say that you added using the `push()` method provided by the `UIViewController` class?
If that is correct, it's not supported.

I hope to add it using the `setViewController()` method as shown below.
```swift
drawerController.setViewController (mainViewController, .none)
drawerController.setViewController (leftViewController, .left)
drawerController.setViewController (rightViewController, .right)
```

**Comment by aiswaryamanal** [comment]
yeah , i used push method and it worked correctly . Now my menu function working. But i need a diiferent style for transition . i want to move my left and right view controller over mainviewcontroller . mainviewController need not to move

**Comment by kawoou** [comment]
Which of the Transitions in `README.md` do you want to apply?

**Comment by aiswaryamanal** [comment]
i don't need any transition from that list

**Comment by aiswaryamanal** [comment]
i want a new one like KYDrawerController

**Comment by kawoou** [comment]
I don't understand what do you want.

**Comment by aiswaryamanal** [comment]
![whatsapp image 2017-12-06 at 4 40 42 pm](https://user-images.githubusercontent.com/33622758/33659259-893dccd0-daa5-11e7-82cb-dd5889c91b17.jpeg)

**Comment by aiswaryamanal** [comment]
i need a drawer like above..

**Comment by aiswaryamanal** [comment]
And the view controller not coming completely.... a portion on left side is lost

**Comment by kawoou** [comment]
In the example code, there is a part of the "absolute" setting.
If you set up this, you can see the effect wanted.

```swift
drawerController.setAbsolute(isAbsolute: true, side: .left)
```

**Comment by aiswaryamanal** [comment]
Then how can i change transition style that i want

**Comment by kawoou** [comment]
That's like below.
I hope you see the example code and run it.

```swift
drawerController.setTransition(transition: DrawerSlideTransition(), side: .left)
```

**Comment by aiswaryamanal** [comment]
I need to stop animation of mainview controller. How can i do it

**Comment by kawoou** [comment]
I don't understand what you mean mainview controller animation.
