### ISSUE TITLE
Use in Objective-C project

### ISSUE THREAD

**Issue by andyden9** [kawoou/KWDrawerController#9]
Hi Kawoou,

I'm using your framework through CocoaPods, I use it exactly as your instruction, but storyboard failed to init DrawerController and returns a plain UIViewController as the initial ViewController. Do you happen to know what's the issue here? Thank you so much in advance!

<img width="575" alt="2018-01-16 6 26 29" src="https://user-images.githubusercontent.com/14224413/34984154-d649d428-faea-11e7-8245-9b5a91a452b7.png">

<img width="251" alt="2018-01-16 6 26 35" src="https://user-images.githubusercontent.com/14224413/34984161-d9fc5988-faea-11e7-8301-03df4b1e289a.png">

<img width="253" alt="2018-01-16 6 26 43" src="https://user-images.githubusercontent.com/14224413/34984165-dd060b42-faea-11e7-8cd6-9a4fa39a3799.png">

<img width="256" alt="2018-01-16 6 26 48" src="https://user-images.githubusercontent.com/14224413/34984175-e6fc4832-faea-11e7-85b3-27bb692955f7.png">

**Comment by kawoou** [comment]
Hi andyden9.
You say mean that even if you specify a "Custom Class" in the identity inspector, it is initialized as if the default UIViewController.

**Comment by andyden9** [comment]
Yes exactly, do you happen to know what caused this? I've stuck on this for more than 5 hrs😭


<img width="1128" alt="2018-01-17 10 52 24" src="https://user-images.githubusercontent.com/14224413/35023196-986864d2-fb74-11e7-884e-1159db44f7e1.png">


<img width="908" alt="2018-01-17 11 14 35" src="https://user-images.githubusercontent.com/14224413/35023883-acdb228a-fb77-11e7-96d7-c7d935a890ff.png">

**Comment by kawoou** [comment]
I mean the ViewController with "left" or "main".
How did you find out that the DrawerController was initialized with a pure UIViewController?

**Comment by andyden9** [comment]
Oh sorry, lol, because I set the DrawerController as the initial View Controller, and after storyboard init, I only got a blank UIViewController as I showed in the debug view hierarchy. Are you busy today? Could you add my wechat(anddddddy) or skype(appleandy94) to instruct me a bit if you're available?

<img width="1128" alt="2018-01-17 10 52 24" src="https://user-images.githubusercontent.com/14224413/35024452-840564e4-fb7a-11e7-84ca-f305532382c2.png">

<img width="908" alt="2018-01-17 11 14 35" src="https://user-images.githubusercontent.com/14224413/35024453-8634df2e-fb7a-11e7-8b4f-4e5b1ddf5de4.png">


I got them all set:
<img width="256" alt="2018-01-16 6 26 48" src="https://user-images.githubusercontent.com/14224413/35024564-295a691c-fb7b-11e7-9013-5c1740a2b1bc.png">
<img width="253" alt="2018-01-16 6 26 43" src="https://user-images.githubusercontent.com/14224413/35024566-298262dc-fb7b-11e7-9014-dbfdac5c7b21.png">
<img width="251" alt="2018-01-16 6 26 35" src="https://user-images.githubusercontent.com/14224413/35024567-29ab1e16-fb7b-11e7-84eb-c4ff92aa03b9.png">


The only difference between your demo and my project I can find is, the demo is a pure swift project, and mine is a pure objective-c project....

**Comment by andyden9** [comment]
Sorry my bad, it seems showing the '😭' label, so DrawerController is inited, I guess the problem is the DrawerController not showing the 'main' controller.

<img width="1295" alt="2018-01-17 11 57 43" src="https://user-images.githubusercontent.com/14224413/35025054-150bf4e6-fb7e-11e7-8e1e-2627ad1c19a6.png">

If it works, simulator should show this:

<img width="1332" alt="2018-01-17 12 02 00" src="https://user-images.githubusercontent.com/14224413/35025097-50db59bc-fb7e-11e7-935b-8ee860c016eb.png">

**Comment by andyden9** [comment]
<img width="1606" alt="2018-01-17 12 33 58" src="https://user-images.githubusercontent.com/14224413/35025878-dff0a73e-fb82-11e7-824d-94b4f60deb56.png">


I found something else, though it's correctly set in the story board as shown(in previous messages), the viewDidLoad method in DrawerController never gets called....

**Comment by kawoou** [comment]
You use the swift library in the objective-c project.
If so, did you specify a bridge header?

This symptom seems to be similar to what happens when a Custom Class is incorrectly specified.

**Comment by andyden9** [comment]
Yes I am using the KWDrawerController as the only swift library in my objective-c project 😱  and I didnt' specify a bridge header since I thought CocoaPods will automatically generate it for me..... I guess that's the issue, let me try to specify a header manually. Thank you Kawoou! 🙏

**Comment by kawoou** [comment]
Fortunately!
Happy Development😆

**Comment by andyden9** [comment]
Hi Kawoou!

Storyboard is still no luck for me so I switched to code, and I've found an issue, that the **setViewController:side:** method in DrawerController maybe duplicated with some system method so OC can't find this method.

After rename this to **setVController:side:** I can use it and everything just work out fine in OC.

May I submit a pull request to fix this? Just name changing.

Cheers,
Andy

**Comment by andyden9** [comment]
<img width="1225" alt="2018-01-17 3 35 56" src="https://user-images.githubusercontent.com/14224413/35031047-517bd7ac-fb9c-11e7-8478-909ea9c7a9e1.png">

**Comment by kawoou** [comment]
It's really weird in objc!

PR is always welcome, even with small modifications 👍 
Thank you for using this project.

**Comment by andyden9** [comment]
Thank you for sharing this great library! I've submitted the PR, please review.
